# Generated by Django 3.1.2 on 2020-11-04 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 3, 30, 48, 62997), verbose_name='date published'),
        ),
    ]
