# Generated by Django 3.1.2 on 2020-11-25 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201124_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 3, 50, 24, 793017), verbose_name='date published'),
        ),
    ]
