# Generated by Django 3.1.2 on 2020-11-25 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201125_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 3, 54, 40, 494332), verbose_name='date published'),
        ),
    ]
