# Generated by Django 3.1.2 on 2020-11-25 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201125_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 4, 24, 6, 868239), verbose_name='date published'),
        ),
    ]
