# Generated by Django 3.1.2 on 2020-11-26 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201125_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 16, 11, 409090), verbose_name='date published'),
        ),
    ]
