# Generated by Django 3.1.2 on 2020-11-26 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201126_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 22, 7, 53976), verbose_name='date published'),
        ),
    ]
