# Generated by Django 3.1.2 on 2020-11-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201126_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 2, 53, 1, 112224), verbose_name='date published'),
        ),
    ]
