# Generated by Django 3.1.2 on 2020-11-26 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201126_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 3, 37, 46, 961241), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='tutorial_series',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
